repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
    - id: check-yaml
    - id: check-added-large-files
    - id: trailing-whitespace
      exclude: ".*(galleria|photoswipe|jquery|leaflet).*$"
    - id: end-of-file-fixer
      exclude: ".*(galleria|photoswipe|jquery|leaflet).*$"

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.1
  hooks:
    - id: pyupgrade
      args: ["--py38-plus"]

- repo: https://github.com/timothycrosley/isort
  rev: 5.12.0
  hooks:
    - id: isort

- repo: https://github.com/psf/black
  rev: 23.1.0
  hooks:
    - id: black

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.246'
  hooks:
    - id: ruff
