repos:

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-yaml
    - id: end-of-file-fixer
      exclude: ".*(galleria|photoswipe|jquery|leaflet).*$"
    - id: trailing-whitespace
      exclude: ".*(galleria|photoswipe|jquery|leaflet).*$"

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.5.2
  hooks:
    - id: ruff
      args: [ --fix, --show-fixes, --exit-non-zero-on-fix ]
    - id: ruff-format
